/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicLeadNotifyRouteImport } from './routes/api/public/lead-notify'
import { Route as AuthenticatedAppVideosRouteImport } from './routes/_authenticated/app.videos'
import { Route as AuthenticatedAppPropertiesRouteImport } from './routes/_authenticated/app.properties'
import { Route as AuthenticatedAppOwnersRouteImport } from './routes/_authenticated/app.owners'
import { Route as AuthenticatedAppLeadListsRouteImport } from './routes/_authenticated/app.lead-lists'
import { Route as AuthenticatedAppContactsRouteImport } from './routes/_authenticated/app.contacts'
import { Route as AuthenticatedAppCampaignsRouteImport } from './routes/_authenticated/app.campaigns'
import { Route as AuthenticatedAppAuctionsRouteImport } from './routes/_authenticated/app.auctions'
import { Route as AuthenticatedAppAgentRouteImport } from './routes/_authenticated/app.agent'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadNotifyRoute = ApiPublicLeadNotifyRouteImport.update({
  id: '/api/public/lead-notify',
  path: '/api/public/lead-notify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppVideosRoute = AuthenticatedAppVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPropertiesRoute =
  AuthenticatedAppPropertiesRouteImport.update({
    id: '/properties',
    path: '/properties',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOwnersRoute = AuthenticatedAppOwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLeadListsRoute =
  AuthenticatedAppLeadListsRouteImport.update({
    id: '/lead-lists',
    path: '/lead-lists',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContactsRoute =
  AuthenticatedAppContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCampaignsRoute =
  AuthenticatedAppCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAuctionsRoute =
  AuthenticatedAppAuctionsRouteImport.update({
    id: '/auctions',
    path: '/auctions',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAgentRoute = AuthenticatedAppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/app/agent': typeof AuthenticatedAppAgentRoute
  '/app/auctions': typeof AuthenticatedAppAuctionsRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/app/contacts': typeof AuthenticatedAppContactsRoute
  '/app/lead-lists': typeof AuthenticatedAppLeadListsRoute
  '/app/owners': typeof AuthenticatedAppOwnersRoute
  '/app/properties': typeof AuthenticatedAppPropertiesRoute
  '/app/videos': typeof AuthenticatedAppVideosRoute
  '/api/public/lead-notify': typeof ApiPublicLeadNotifyRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/app/agent': typeof AuthenticatedAppAgentRoute
  '/app/auctions': typeof AuthenticatedAppAuctionsRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/app/contacts': typeof AuthenticatedAppContactsRoute
  '/app/lead-lists': typeof AuthenticatedAppLeadListsRoute
  '/app/owners': typeof AuthenticatedAppOwnersRoute
  '/app/properties': typeof AuthenticatedAppPropertiesRoute
  '/app/videos': typeof AuthenticatedAppVideosRoute
  '/api/public/lead-notify': typeof ApiPublicLeadNotifyRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/app/agent': typeof AuthenticatedAppAgentRoute
  '/_authenticated/app/auctions': typeof AuthenticatedAppAuctionsRoute
  '/_authenticated/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/_authenticated/app/contacts': typeof AuthenticatedAppContactsRoute
  '/_authenticated/app/lead-lists': typeof AuthenticatedAppLeadListsRoute
  '/_authenticated/app/owners': typeof AuthenticatedAppOwnersRoute
  '/_authenticated/app/properties': typeof AuthenticatedAppPropertiesRoute
  '/_authenticated/app/videos': typeof AuthenticatedAppVideosRoute
  '/api/public/lead-notify': typeof ApiPublicLeadNotifyRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/features'
    | '/pricing'
    | '/sitemap.xml'
    | '/app'
    | '/dashboard'
    | '/api/chat'
    | '/email/unsubscribe'
    | '/app/agent'
    | '/app/auctions'
    | '/app/campaigns'
    | '/app/contacts'
    | '/app/lead-lists'
    | '/app/owners'
    | '/app/properties'
    | '/app/videos'
    | '/api/public/lead-notify'
    | '/lovable/email/suppression'
    | '/app/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/features'
    | '/pricing'
    | '/sitemap.xml'
    | '/dashboard'
    | '/api/chat'
    | '/email/unsubscribe'
    | '/app/agent'
    | '/app/auctions'
    | '/app/campaigns'
    | '/app/contacts'
    | '/app/lead-lists'
    | '/app/owners'
    | '/app/properties'
    | '/app/videos'
    | '/api/public/lead-notify'
    | '/lovable/email/suppression'
    | '/app'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/features'
    | '/pricing'
    | '/sitemap.xml'
    | '/_authenticated/app'
    | '/_authenticated/dashboard'
    | '/api/chat'
    | '/email/unsubscribe'
    | '/_authenticated/app/agent'
    | '/_authenticated/app/auctions'
    | '/_authenticated/app/campaigns'
    | '/_authenticated/app/contacts'
    | '/_authenticated/app/lead-lists'
    | '/_authenticated/app/owners'
    | '/_authenticated/app/properties'
    | '/_authenticated/app/videos'
    | '/api/public/lead-notify'
    | '/lovable/email/suppression'
    | '/_authenticated/app/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FeaturesRoute: typeof FeaturesRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicLeadNotifyRoute: typeof ApiPublicLeadNotifyRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead-notify': {
      id: '/api/public/lead-notify'
      path: '/api/public/lead-notify'
      fullPath: '/api/public/lead-notify'
      preLoaderRoute: typeof ApiPublicLeadNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/videos': {
      id: '/_authenticated/app/videos'
      path: '/videos'
      fullPath: '/app/videos'
      preLoaderRoute: typeof AuthenticatedAppVideosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/properties': {
      id: '/_authenticated/app/properties'
      path: '/properties'
      fullPath: '/app/properties'
      preLoaderRoute: typeof AuthenticatedAppPropertiesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/owners': {
      id: '/_authenticated/app/owners'
      path: '/owners'
      fullPath: '/app/owners'
      preLoaderRoute: typeof AuthenticatedAppOwnersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/lead-lists': {
      id: '/_authenticated/app/lead-lists'
      path: '/lead-lists'
      fullPath: '/app/lead-lists'
      preLoaderRoute: typeof AuthenticatedAppLeadListsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/contacts': {
      id: '/_authenticated/app/contacts'
      path: '/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AuthenticatedAppContactsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/campaigns': {
      id: '/_authenticated/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AuthenticatedAppCampaignsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/auctions': {
      id: '/_authenticated/app/auctions'
      path: '/auctions'
      fullPath: '/app/auctions'
      preLoaderRoute: typeof AuthenticatedAppAuctionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agent': {
      id: '/_authenticated/app/agent'
      path: '/agent'
      fullPath: '/app/agent'
      preLoaderRoute: typeof AuthenticatedAppAgentRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAgentRoute: typeof AuthenticatedAppAgentRoute
  AuthenticatedAppAuctionsRoute: typeof AuthenticatedAppAuctionsRoute
  AuthenticatedAppCampaignsRoute: typeof AuthenticatedAppCampaignsRoute
  AuthenticatedAppContactsRoute: typeof AuthenticatedAppContactsRoute
  AuthenticatedAppLeadListsRoute: typeof AuthenticatedAppLeadListsRoute
  AuthenticatedAppOwnersRoute: typeof AuthenticatedAppOwnersRoute
  AuthenticatedAppPropertiesRoute: typeof AuthenticatedAppPropertiesRoute
  AuthenticatedAppVideosRoute: typeof AuthenticatedAppVideosRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAgentRoute: AuthenticatedAppAgentRoute,
  AuthenticatedAppAuctionsRoute: AuthenticatedAppAuctionsRoute,
  AuthenticatedAppCampaignsRoute: AuthenticatedAppCampaignsRoute,
  AuthenticatedAppContactsRoute: AuthenticatedAppContactsRoute,
  AuthenticatedAppLeadListsRoute: AuthenticatedAppLeadListsRoute,
  AuthenticatedAppOwnersRoute: AuthenticatedAppOwnersRoute,
  AuthenticatedAppPropertiesRoute: AuthenticatedAppPropertiesRoute,
  AuthenticatedAppVideosRoute: AuthenticatedAppVideosRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FeaturesRoute: FeaturesRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicLeadNotifyRoute: ApiPublicLeadNotifyRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
